"""Research state — the shared object flowing through the LangGraph pipeline.

All nodes read from and write to this TypedDict. LangGraph handles
merging: fields typed with Annotated[list, operator.add] accumulate
across node calls rather than overwriting.
"""

import operator
from typing import Annotated

from langchain_core.messages import BaseMessage
from typing_extensions import TypedDict


class ResearchState(TypedDict):
    """Shared state passed through every node in the research graph.

    Attributes:
        query: The original user research question.
        sub_queries: Targeted sub-questions generated by the Query Planner.
        sources_to_use: Source identifiers chosen by the Planner
            (e.g. ["arxiv", "tavily", "wikipedia"]).
        messages: Accumulating LLM conversation history across all nodes.
        retrieved_documents: All document chunks pulled from retrieval tools.
            Each dict contains: source, title, url, content, metadata.
        analysis_summary: Synthesized summary produced by the Analyzer.
        contradictions: List of conflicting claims found across sources.
        validated_sources: Source URLs/IDs deemed credible by the Analyzer.
        insights: Hypotheses and trends generated by the Insight Generator.
        final_report: The complete Markdown report from the Report Builder.
        retrieval_attempts: Counter tracking how many retrieval rounds ran,
            used by the conditional edge to cap retry loops at 3.
        status: Human-readable label for the current pipeline stage.
        pdf_paths: Optional list of local PDF file paths to include.
    """

    query: str
    sub_queries: list[str]
    sources_to_use: list[str]
    messages: Annotated[list[BaseMessage], operator.add]
    retrieved_documents: Annotated[list[dict], operator.add]
    analysis_summary: str
    contradictions: list[str]
    validated_sources: list[str]
    insights: list[str]
    final_report: str
    retrieval_attempts: int
    status: str
    pdf_paths: list[str]
