"""
state.py — Shared State Schema for Multi-Agent Deep Researcher
All agents read from and write to this TypedDict.
LangGraph serializes / deserializes this between nodes.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ──────────────────────────────────────────────
# Enums
# ──────────────────────────────────────────────

class AgentStatus(str, Enum):
    PENDING   = "pending"
    RUNNING   = "running"
    DONE      = "done"
    FAILED    = "failed"
    SKIPPED   = "skipped"


class SourceType(str, Enum):
    WEB       = "web"
    ARXIV     = "arxiv"
    NEWS      = "news"
    API       = "api"
    CACHED    = "cached"


# ──────────────────────────────────────────────
# Sub-models (Pydantic for validation)
# ──────────────────────────────────────────────

class Source(BaseModel):
    """A single retrieved source with metadata."""
    id: str
    title: str
    url: str
    content: str
    snippet: str
    source_type: SourceType
    domain: str = ""
    published_date: Optional[str] = None
    credibility_score: float = 0.5      # 0-1, assigned by Analyzer
    relevance_score: float  = 0.5       # 0-1, assigned by Retriever
    citations: int = 0                   # for arxiv papers
    is_verified: bool = False


class Contradiction(BaseModel):
    """A conflict found between two or more sources."""
    claim_a: str
    source_a_id: str
    claim_b: str
    source_b_id: str
    explanation: str
    severity: str = "medium"            # low | medium | high


class Insight(BaseModel):
    """A hypothesis or trend generated by the Insight Agent."""
    hypothesis: str
    reasoning_chain: List[str]          # step-by-step CoT
    supporting_source_ids: List[str]
    confidence: float = 0.5             # 0-1
    category: str = "trend"            # trend | risk | opportunity | gap


class ClarificationQuestion(BaseModel):
    """A follow-up question posed by the Query Clarifier Agent."""
    question: str
    purpose: str
    answered: bool = False
    answer: Optional[str] = None


class VisualizationSpec(BaseModel):
    """Specification for a chart/graph to be rendered."""
    chart_type: str                     # bar | line | scatter | pie | heatmap
    title: str
    description: str
    data: Dict[str, Any]
    file_path: Optional[str] = None     # set after rendering


class AgentLog(BaseModel):
    """Execution log entry for a single agent run."""
    agent_name: str
    status: AgentStatus
    started_at: Optional[str] = None
    finished_at: Optional[str] = None
    tokens_used: int = 0
    error: Optional[str] = None
    notes: str = ""


# ──────────────────────────────────────────────
# Master State — passed between ALL nodes
# ──────────────────────────────────────────────

class ResearchState(BaseModel):
    """
    The single source of truth for the entire research pipeline.
    Every agent reads from and writes back to this object.
    LangGraph checkpoints this between node transitions.
    """

    # ── Input ──────────────────────────────────
    original_query: str = ""
    clarified_query: str = ""           # set after Query Clarifier runs
    sub_queries: List[str] = Field(default_factory=list)

    # ── Clarification loop ──────────────────────
    clarification_questions: List[ClarificationQuestion] = Field(default_factory=list)
    clarification_needed: bool = False
    clarification_complete: bool = False
    user_clarification_input: Optional[str] = None  # populated from API when user answers

    # ── Retrieval ───────────────────────────────
    raw_sources: List[Source] = Field(default_factory=list)
    rag_chunks: List[Dict[str, Any]] = Field(default_factory=list)  # embedded chunks
    rag_collection_name: str = ""

    # ── Analysis ────────────────────────────────
    verified_sources: List[Source] = Field(default_factory=list)
    contradictions: List[Contradiction] = Field(default_factory=list)
    summary_per_source: Dict[str, str] = Field(default_factory=dict)
    cross_source_summary: str = ""
    fact_check_results: Dict[str, Any] = Field(default_factory=dict)

    # ── Insights ────────────────────────────────
    insights: List[Insight] = Field(default_factory=list)
    key_themes: List[str] = Field(default_factory=list)
    data_points: List[Dict[str, Any]] = Field(default_factory=list)  # for visualizer

    # ── Report ──────────────────────────────────
    final_report_md: str = ""
    final_report_path: Optional[str] = None

    # ── Visualizations ──────────────────────────
    visualization_specs: List[VisualizationSpec] = Field(default_factory=list)
    visualization_paths: List[str] = Field(default_factory=list)

    # ── Orchestration meta ──────────────────────
    agent_logs: List[AgentLog] = Field(default_factory=list)
    iteration: int = 0                  # how many retrieval→analysis loops
    max_iterations: int = 2
    needs_more_research: bool = False   # orchestrator can loop back
    pipeline_complete: bool = False
    error_message: Optional[str] = None

    class Config:
        arbitrary_types_allowed = True
